import {NativeStackNavigationOptions} from '@react-navigation/native-stack';
import {responsiveWidth} from 'react-native-responsive-dimensions';

export enum AppRoutes {
  //auth
  getStarted = 'getStarted',
  forgotPassword = 'forgotPassword',
  forgotPasswordOTP = 'forgotPasswordOTP',
  login = 'login',
  otpVerification = 'otpVerification',
  register = 'register',
  registerSuccess = 'registerSuccess',
  addAVehicle = 'addAVehicle',
  changePassword = 'changePassword',
  //Main
  bottomTabRoutes = 'bottomTabRoutes',
  homeTab = 'homeTab',
  home = 'home',
  cancelBooking = 'cancelBooking',
  wallet = 'wallet',
  myBookingsTab = 'myBookingsTab',
  notification = 'notification',
  profile = 'profile',
  inviteFriends = 'inviteFriends',
  about = 'about',
  support = 'support',
  termsAndConditions = 'termsAndConditions',
  privacy = 'privacy',
  drawerTabRoutes = 'drawerTabRoutes',
  editProfile = 'editProfile',
  services = 'services',
  serviceDetails = 'serviceDetails',
  location = 'location',
  bookingDetails = 'bookingDetails',
  paymentMethod = 'paymentMethod',
  applyCoupon = 'applyCoupon',
  paymentDetails = 'paymentDetails',
  reschedule = 'reschedule',
  referralRewards = 'referralRewards',
  rateUs = 'rateUs',
}
export const AppNavigationOptions: NativeStackNavigationOptions = {
  headerShown: false,
  gestureEnabled: false,
  fullScreenGestureEnabled: false,
  // animationEnabled: false,
  // gestureResponseDistance: responsiveWidth(10),
};

export enum AppStrings {
  carWash = 'CarWash',
  getStarted = 'GET STARTED',
  carWashDesc = 'A convenient solution for car and bike owners to book washing services for their vehicles directly through their smartphones.',
  register = 'REGISTER',
  name = 'Name',
  confirm = 'confirm',
  enterPassword = 'Enter Your Password',
  password = 'Password',
  confirmPassword = 'Confirm Password',
  reEnterYourPassword = 'Re-Enter your Password',
  enterYourName = 'Enter your name',
  mobileNumber = 'Mobile Number',
  brand = 'Brand',
  model = 'Model',
  selectBrand = 'Select Brand',
  selectModel = 'Select Model',
  plateNumber = 'Plate Number(Optional)',
  enterVehicleNumber = 'Enter Vehicle Number',
  selectColor = 'Select Color',
  saveVehicle = 'Save Vehicle',
  orContinueWithSocial = 'Or, Continue With Social',
  enterEmail2 = 'Enter your registered mobile number',
  send = 'SEND',
  otpVerification = 'OTP VERIFICATION',
  youAreRegistered = 'You are Registered Successfully',
  login2 = 'LOGIN',
  submit = 'SUBMIT',
  profile = 'PROFILE',
  email = 'Email (Optional)',
  email2 = 'Email',
  address = 'Address',
  editProfile = 'EDIT PROFILE',
  changePicture = 'Change Picture',
  update = 'UPDATE',
  notification = 'NOTIFICATION',
  noNotifications = 'No Notifications',
  weWillLet = 'We’ll let you know when there will be something to update you.',
  forgotPassword = 'FORGOT PASSWORD?',
  addAVehicle = 'ADD A VEHICLE',
  wallet = 'WALLET',
  walletBalance = 'Wallet Balance',
  walletCoins = 'Wallet coins',
  myRefferals = 'My Referrals',
  walletHistory = 'Wallet History',
  referralRewards = 'REFERRAL REWARDS',
  referFriends = 'Refer Friends & Earn',
  add = 'Add',
  reschedule = 'Reschedule',
  cancelBooking = 'Cancel Booking',
  ok = 'OKAY',
  howRefer = 'How Refer and Earn Works',
  pressureCarWash = 'Pressure Car wash',
  includedServices = 'Included Services',
  myBookings = 'MY BOOKINGS',
  upcoming = 'Upcoming',
  completed = 'Completed',
  canceled = 'Canceled',
  dayDate = 'Day & Date',
  timing = 'Timing',
  vehicle = 'Vehicle',
  servicePerson = 'Service Person',
  shareThisOtp = 'Share this OTP number with service person',
  rateUs = 'Rate Us',
  serviceBy = 'Service By',
  done = 'DONE',
  selectReasonForCancelation = 'Select Reason for Cancelation',
  myLocation = 'My location',
  searchServices = 'Search services',
  services = 'Services',
  seeAll = 'See all',
  categories = 'Categories',
  home = 'Home',
  paymentMethod = 'PAYMENT METHOD',
  choosePaymentMethod = 'Choose A Payment Method',
  creditCard = 'Credit Card',
  mastercard = 'Mastercard',
  visa = 'Visa',
  addNewCard = 'Add new card',
  proceedToPay = 'Proceed to Pay',
  offers = 'Offers',
  applyCoupon = 'Apply Coupon',
  enterCouponCode = 'Enter Coupon Code',
  apply = 'Apply',
  flatdeal = 'FLATDEAL',
  paymentDetails = 'Payment Details',
  paymentReceived = 'Payment Received Successfully!',
  congratulations = `Congratulations\nYour booking has been confirmed.`,
  paymentReceipt = 'Payment Receipt',
  backToHome = 'BACK TO HOME',
  logout = 'Logout',
  logout2 = 'Log Out',
  privacyPolicy = 'Privacy Policy',
  termsAndConditions = 'Terms & Conditions',
  support = 'Support',
  aboutUs = 'About Us',
  inviteFriends = 'Invite Friends',
  myWallet = 'My Wallet',
  cancel = 'Cancel',
  location = 'Location',
  pickup = 'PICKUP',
  dropoff = 'DROP-OFF',
  bookingDetails = 'Booking Details',
  rescheduleBooking = 'Reschedule Booking',
  myCurrentLocation = 'My current location',
  selectDateAndDay = 'Select Date & Day',
  selectTimeSlot = 'Select Time Slot',
  yourLocation = 'Your location',
  bookASlot = 'Book A Slot',
  booking = 'Booking',
  okay = 'Okay',
  areYouSure = `Are you sure you want to log out? You'll need to login again to use the app.`,
  changePassword = 'Change Password',
  // dummy
  login = 'Log In',
  year = 'Year',
  week = 'Week',
  averageHistory = 'Average Reading History',
  limitHistory = 'Limit crossed history ',
  emailOrNumber = 'Email ID or Mobile No.',
  enterYourNumber = 'Enter your Mobile Number',
  dontHaveAccount = "Don't have account?",
  signUp = 'SIGN UP',
  machineId = 'Machine ID',
  enterMachineId = 'Enter Machine ID',
  statistics = 'Statistics',
  enterEmail = 'Enter your registered Email',
  rememberPassword = 'Remember Password?',
  shareYourExperience = 'Share your experience in scaling',
  rateYourExperience = 'Rate your Experience',
  careToShare = 'Care to Share more about it?',
  howWasYourOverall = 'How was your overall experience?',
  selectYourVehicle = 'Select your type of vehicle.',
  weWillSend = 'We will send you a One Time Password on this mobile number',
  notReceivedOTP = "Didn't receive OTP?",
  resend = 'RESEND',
  powerCunsumption = 'Power Consumption',
  enterYourEmail = 'Enter your email',
  existingUser = 'Existing User?',
  bySelecting = 'By selecting Continue below, I agree to the above Terms & Conditions.',
  wehaveSentPassword = 'We have sent a system generated password to your registered mobile number.',
  subscriptionPlan = 'Subscription Plan',
  startFree = 'Start FREE',
  twoMonths = '2 month Trial',
  annualPlan = 'Annual Plan',
  billedAnnally = 'Billed Annually',
  subscribeNow = 'SUBSCRIBE NOW',
  meterReading = 'Meter Reading',
  liveReading = 'Get Live Reading',
  history = 'History',
  sortBy = 'Sort By',
  date = 'Date',
  reading = 'Reading',
  meterName = 'Meter Name',
  readingBy = 'Reading By',
  type = 'Type',
  requestId = 'Request ID',
  month = 'Month',
  statistics2 = 'STATISTICS',
  inputVoltage = 'Input Voltage',
  outputVoltage = 'Output Voltage',
  temperature = 'Temperature',
  inputFrequency = 'Input Frequency',
  exportToXL = 'Export to Excel',
  getOTP = 'GET OTP',
  bookService = 'Book Service',
}

export enum SubscriptionConstants {
  //auth
  free = 'free',
  annual = 'annual',
}

export const redux = {
  API_LOGIN_SAGA: 'API_LOGIN_SAGA',
  API_REGISTER_SAGA: 'API_REGISTER_SAGA',
  API_REGISTER_OTP_VERIFY_SAGA: 'API_REGISTER_OTP_VERIFY_SAGA',
  API_FORGOT_PASSWORD_SAGA: 'API_FORGOT_PASSWORD_SAGA',
  API_FORGOT_PASSWORD_OTP_VERIFY_SAGA: 'API_FORGOT_PASSWORD_OTP_VERIFY_SAGA',
  API_CHANGE_PASSWORD_SAGA: 'API_CHANGE_PASSWORD_SAGA',

  IS_LOADING: 'IS_LOADING',
  USER_DATA_UPDATE: 'USER_DATA_UPDATE',
  APP_FIRST_TIME_OPENED_UPDATE: 'APP_FIRST_TIME_OPENED_UPDATE',
  LOGOUT: 'LOGOUT',
};
